### PR TITLE
added support for multiple logins per user

### PR DESCRIPTION
**Pull request by stuisme**
added the ability to associate more external logins to a user. I have also updated the templates and such for the MVC-SPA-angular project to support these new features. I would be glad to submit a pull request to that repo if you decide to update this nuget package.

### CODE REVIEW

**Comment by JustMaier** [comment]
Please submit a pull request there as well. I'd like to see what adjustments you had to make to the template.

I'm actually in the process of revamping the template to add support for:
- Two Factor Auth
- Reset Password
- Confirm Email
- Account Lockout

**Comment by JustMaier** [comment]
Did you have to make any changes on the backend web api to get this to work?

**Comment by stuisme** [comment]
I have submitted https://github.com/JustMaier/MVC5-SPA-Angular/pull/6 with the other updates.

No updates to the backend.

**Comment by stuisme** [comment]
Are you having issues? I am running the updated MVC pull request

**Comment by JustMaier** [comment]
No issues! Thanks for the great addition.

I'll create the nuget package and pull the updates for the template in a moment.

**Pull request merged**
