### PR TITLE
change to check login, and log out

### PR DESCRIPTION
**Pull request by luiscaiano**
- added version information
- when retrieving UserInfo, on any error it should logout/ request a new authentication
- logout should always log out, in client, even if the server does not acknowledge it
- code clean up and minify

### CODE REVIEW

**Comment by luiscaiano** [comment]
incorrectly accessed getUserInfo user data

**Comment by JustMaier** [comment]
Hey @luiscaiano, thanks for the PR - unfortunately since it looks like you may have changed from tabs to spaces it's kind of hard to tell what actually changed. Do you think you can switch it back to tabs so I can review it?

**Comment by luiscaiano** [comment]
Hay @JustMaier, sure, will do something... 
may be easy-er to reject it all together, and i resubmit changes.

**Comment by JustMaier** [comment]
Ok @luiscaiano, I'll reject this for now then.

**Pull request closed without merging**
